# ------------------------------
# Copyright (c) PiggyPiglet 2017
# https://www.piggypiglet.me
# ------------------------------
# This is the default config for RandomSpawn.
# You can add more locations in the location section.
# locations:
#   Swamp:
#     world: survival
#     x: 632
#     y: 10
#     z: 31
#     yaw: 2
#     pitch: 7
#   Bush:
#     world: hub
#     x: 4321
#     y: 120
#     z: 951
#     yaw: 4
#     pitch: 1
#   Clay:
#     world: world
#     x: 66123
#     y: 109
#     z: 392
#     yaw: 5
#     pitch: 1
settings:
  chat:
    PREFIX: "&7[&cRS&7] "
    NOPERM: "&7No permission for that command."
    UNKNOWNSUB: "&7Unknown subcommand."
    ONLYPLAYER: "&7This command can only be executed by a player!"
    DOESNTEXIST: "&7The location you specified does not exist."
    TOOMUCHARGS: "&7Too many arguments!"
    RESPAWN: "&7There are no locations defined in config for respawning! You will respawn at the default location."
data:
  locations:
    name:
      world: world
      x: 10
      y: 100
      z: 10
      yaw: 4
      pitch: 4
      respawn: true
      disabled: false