name: RandomSpawn
version: 2.0.0
description: A plugin that spawns you at a random set location on join.
author: PiggyPiglet
website: https://www.piggypiglet.me
main: me.piggypiglet.rs.RandomSpawn
commands:
  rs:
    description: Help for RandomRespawn
    usage: /rs
    permission: randomspawn.randomspawn
    permission-message: No permission, ask your administator to add <permission> if you think this is an error.