name: RandomSpawn
version: 1.2.0
description: A plugin that spawns you at a random set location on join.
author: PiggyPiglet
website: https://www.piggypiglet.me
main: me.piggypiglet.rs.RandomSpawn
commands:
  rs:
    description: Help for RandomRespawn
    usage: /rs
  rssetspawn:
    description: Set spawn command
    usage: /rssetspawn [location name]